-- Importação de relatórios de scanner.
--
-- Two tables and one column. The tables hold the staging area of an import — the report that
-- was uploaded and every finding it contained — and the column is what makes deduplication a
-- property of the database instead of a rule the service promises to remember.
--
-- The staging area exists because the matching between a finding's target and an asset is not
-- something a machine can finish on its own: a scanner reports "10.0.0.11" and this product
-- knows assets by an identifier a person typed. The rows below are what lets that person see
-- the result, fix the rows that did not match, and only then decide whether any vulnerability
-- is created at all.

CREATE TABLE scan_imports (
    id                BIGSERIAL PRIMARY KEY,
    company_id        BIGINT       NOT NULL,
    -- The project the report was imported into, and the scope in which a finding's target is
    -- resolved to an asset: the identifier of an asset is unique inside a project (V4), so
    -- "which project" is part of the question "which asset is this".
    --
    -- Unlike vulnerabilities, the project IS stored here, and it is not a denormalization that
    -- can go stale. An asset may be moved between projects; an import cannot. It records the
    -- project the operator chose at the time of the upload, which is a historical fact.
    project_id        BIGINT       NOT NULL,
    -- Declared by the caller, never sniffed from the bytes: see the javadoc of ScanFormat.
    -- The CHECK duplicates the enum so a row written by a seed or a future importer cannot
    -- claim a layout no parser can read.
    format            VARCHAR(20)  NOT NULL,
    -- The name the client sent, sanitized by AttachmentFilenameSanitizer. It is a label shown
    -- in the history and nothing else: no path is ever built from it.
    original_filename VARCHAR(255) NOT NULL,
    -- The name on disk. A UUID without dashes, generated by the server, exactly like V8.
    stored_filename   VARCHAR(32)  NOT NULL,
    size_bytes        BIGINT       NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    -- Summary counters, denormalized from scan_findings.
    --
    -- They are a cache of six GROUP BY counts and they are kept because the history listing
    -- shows all six for every row: reading them from the findings would make a page of twenty
    -- imports twenty aggregate queries, or one join that returns one row per finding. The
    -- service recomputes them in the same transaction that changes a finding's status, so the
    -- cache and the rows it summarizes commit together or not at all.
    total_findings    INTEGER      NOT NULL DEFAULT 0,
    matched_count     INTEGER      NOT NULL DEFAULT 0,
    unmatched_count   INTEGER      NOT NULL DEFAULT 0,
    duplicate_count   INTEGER      NOT NULL DEFAULT 0,
    imported_count    INTEGER      NOT NULL DEFAULT 0,
    skipped_count     INTEGER      NOT NULL DEFAULT 0,
    imported_by       BIGINT,
    created_at        TIMESTAMPTZ  NOT NULL,
    updated_at        TIMESTAMPTZ  NOT NULL,
    -- company_id is denormalized like everywhere else in this schema: every read of this table
    -- filters by tenant, and reaching the company through projects would put a join on the
    -- path of the history listing.
    CONSTRAINT fk_scan_imports_company FOREIGN KEY (company_id) REFERENCES companies (id),
    -- No ON DELETE CASCADE, for the same reason as V5 and V8: deleting a project has to be a
    -- conflict the service reports, not a silent removal of the import history of that project.
    CONSTRAINT fk_scan_imports_project FOREIGN KEY (project_id) REFERENCES projects (id),
    -- Nullable: deactivating or removing the person who ran the import must not erase the
    -- record that the import happened.
    CONSTRAINT fk_scan_imports_imported_by FOREIGN KEY (imported_by) REFERENCES users (id),
    CONSTRAINT ck_scan_imports_format
        CHECK (format IN ('NMAP_XML', 'ZAP_JSON', 'NUCLEI_JSONL')),
    CONSTRAINT ck_scan_imports_status
        CHECK (status IN ('PENDING', 'CONFIRMED', 'DISCARDED')),
    CONSTRAINT ck_scan_imports_size CHECK (size_bytes > 0),
    CONSTRAINT ck_scan_imports_original_filename CHECK (length(btrim(original_filename)) > 0),
    -- The same shape V8 enforces, and for the same reason: a bug that tried to store the
    -- client's own filename — the first step of every path traversal — cannot persist, because
    -- only the 32 hex characters the server generates satisfy this.
    CONSTRAINT ck_scan_imports_stored_filename CHECK (stored_filename ~ '^[0-9a-f]{32}$'),
    -- A negative counter is a bug in the recomputation, and it is cheaper to find here than in
    -- a screen that shows "-1 achados duplicados".
    CONSTRAINT ck_scan_imports_counters CHECK (
        total_findings >= 0 AND matched_count >= 0 AND unmatched_count >= 0
            AND duplicate_count >= 0 AND imported_count >= 0 AND skipped_count >= 0)
    -- There is deliberately no upper bound on size_bytes nor on total_findings here. Both are
    -- tunables (securityhub.scan.max-upload-bytes, securityhub.scan.max-findings) and a CHECK
    -- would be the one copy of the limit that cannot be lowered without a new migration.
);

-- The name on disk is the identity of the file; two rows pointing at one file would make the
-- discard of either one destroy the report of the other.
CREATE UNIQUE INDEX uq_scan_imports_stored_filename ON scan_imports (stored_filename);

-- Covers the history listing, which is the only paged read of this table: the imports of one
-- company, newest first. Prefixed by company_id because no query here crosses the tenant
-- boundary, and DESC so the default ordering is read straight off the index.
CREATE INDEX idx_scan_imports_company_created_at ON scan_imports (company_id, created_at DESC);

CREATE TABLE scan_findings (
    id               BIGSERIAL PRIMARY KEY,
    company_id       BIGINT        NOT NULL,
    import_id        BIGINT        NOT NULL,
    -- Scanner-side rule identity: NSE script id, ZAP pluginid, nuclei template-id. Nullable
    -- because a report may omit it, and a finding without a rule id is still a finding.
    rule_id          VARCHAR(200),
    -- The next four columns mirror vulnerabilities (V5) exactly, including their CHECKs. That
    -- is the point: a finding row must already satisfy every rule the vulnerability it may
    -- become will have to satisfy. The import service builds the vulnerability entity directly,
    -- so Bean Validation never runs on it — if an illegal value could live here, it would only
    -- surface on confirm, as a DataIntegrityViolationException the global handler answers with
    -- a 409 about a conflict that does not exist. Catching it at the staging row instead means
    -- the failure happens at the upload, on the row the operator can see.
    title            VARCHAR(200)  NOT NULL,
    description      VARCHAR(4000),
    severity         VARCHAR(20)   NOT NULL,
    cvss_score       NUMERIC(3, 1),
    cve              VARCHAR(20),
    -- The host, IP or URL the scanner reported. Wider than assets.identifier (255) on purpose:
    -- a ZAP instance URI carries a full query string and is routinely longer than any
    -- identifier a person would type. A target longer than 255 simply cannot match an asset,
    -- and it still has to be shown so the operator can map it by hand.
    target           VARCHAR(2000),
    discovered_at    TIMESTAMPTZ   NOT NULL,
    -- sha256hex(scanner:ruleId:target:cve); see ScanNormalizer.fingerprint for what is in it
    -- and, more importantly, what is deliberately not.
    --
    -- VARCHAR(64) and not CHAR(64): V8 had to annotate its checksum with
    -- columnDefinition = "bpchar(64)" because pgjdbc reports CHAR as bpchar and ddl-auto
    -- validate compares type names. That workaround is a cost with no benefit — CHAR pads and
    -- compares ignoring trailing spaces, which is a bad fit for a value compared against
    -- vulnerabilities.fingerprint below. Both columns are VARCHAR(64), so the comparison behind
    -- the deduplication is between two identical types.
    fingerprint      VARCHAR(64)   NOT NULL,
    -- Null until the finding is matched, either automatically by identifier or by hand on the
    -- preview screen. An unmatched finding is a normal, expected state: the importer never
    -- creates an asset on its own.
    asset_id         BIGINT,
    status           VARCHAR(20)   NOT NULL,
    -- Set exactly when the finding becomes a vulnerability, which is what makes this table the
    -- per-finding traceability of the import. The audit trail carries one row for the whole
    -- import; the answer to "where did this vulnerability come from" lives here.
    vulnerability_id BIGINT,
    created_at       TIMESTAMPTZ   NOT NULL,
    updated_at       TIMESTAMPTZ   NOT NULL,
    CONSTRAINT fk_scan_findings_company FOREIGN KEY (company_id) REFERENCES companies (id),
    -- No ON DELETE CASCADE: nothing deletes an import today, and the day something does, the
    -- rule belongs in a service that can also decide what happens to the file on disk.
    CONSTRAINT fk_scan_findings_import FOREIGN KEY (import_id) REFERENCES scan_imports (id),
    CONSTRAINT fk_scan_findings_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
    CONSTRAINT fk_scan_findings_vulnerability FOREIGN KEY (vulnerability_id) REFERENCES vulnerabilities (id),
    CONSTRAINT ck_scan_findings_status
        CHECK (status IN ('MATCHED', 'UNMATCHED', 'DUPLICATE', 'IMPORTED', 'SKIPPED')),
    -- Copied from V5 verbatim, along with the two below.
    CONSTRAINT ck_scan_findings_severity CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_scan_findings_cvss
        CHECK (cvss_score IS NULL OR (cvss_score >= 0 AND cvss_score <= 10)),
    CONSTRAINT ck_scan_findings_cve CHECK (cve IS NULL OR cve ~ '^CVE-[0-9]{4}-[0-9]{4,}$'),
    CONSTRAINT ck_scan_findings_title CHECK (length(btrim(title)) > 0),
    -- Lowercase hex, the only thing ScanNormalizer.fingerprint can produce. A fingerprint in
    -- another case would compare unequal to a vulnerability's and silently defeat the
    -- deduplication instead of failing.
    CONSTRAINT ck_scan_findings_fingerprint CHECK (fingerprint ~ '^[0-9a-f]{64}$'),
    -- A finding that claims to be matched has to say to what. The reverse is not asserted:
    -- a DUPLICATE or a SKIPPED finding may perfectly well have matched an asset, and forgetting
    -- which asset it was would throw away the only useful thing about it.
    CONSTRAINT ck_scan_findings_status_asset
        CHECK (status NOT IN ('MATCHED', 'IMPORTED') OR asset_id IS NOT NULL),
    -- The equivalence, in the style of ck_vulnerabilities_resolved_at: IMPORTED implies a
    -- vulnerability and every other status implies its absence. Enforced here and not only in
    -- the service so a bug in confirm cannot leave a finding that claims to have been imported
    -- without saying into what.
    CONSTRAINT ck_scan_findings_status_vulnerability
        CHECK ((status = 'IMPORTED') = (vulnerability_id IS NOT NULL))
);

-- Covers the only read of this table: every finding of one import, in insert order. Prefixed
-- by company_id like every other index of the schema.
CREATE INDEX idx_scan_findings_company_import ON scan_findings (company_id, import_id);

-- The deduplication key.
--
-- Nullable because it only means something for a finding that came from a scanner: a
-- vulnerability someone typed by hand has no fingerprint, and giving it one would be inventing
-- a scanner identity for a finding no scanner reported.
ALTER TABLE vulnerabilities ADD COLUMN fingerprint VARCHAR(64);

-- Same shape rule as the staging column, for the same reason.
ALTER TABLE vulnerabilities ADD CONSTRAINT ck_vulnerabilities_fingerprint
    CHECK (fingerprint IS NULL OR fingerprint ~ '^[0-9a-f]{64}$');

-- This index does two jobs, and the second is the one worth having.
--
-- The first is speed: marking duplicates reads every fingerprint of a report against this
-- company, which is an index lookup instead of a sequential scan of the busiest table.
--
-- The second is that it makes "never import the same finding twice" a guarantee of the
-- database rather than a rule of ScanImportService. The service skips duplicates, and it is
-- right to — but a second importer, a concurrent confirm of two imports of the same report, or
-- a future bulk endpoint would each need to remember the same rule. Here, the second insert
-- fails, and it fails whoever writes it.
--
-- Partial on fingerprint IS NOT NULL because the column is null for every hand-written finding:
-- without the WHERE clause, the second manually created vulnerability of a company would
-- collide with the first on a shared NULL in engines that treat NULLs as equal, and would
-- bloat the index with rows it can never be asked about in the ones that do not.
CREATE UNIQUE INDEX uk_vulnerabilities_company_fingerprint
    ON vulnerabilities (company_id, fingerprint)
    WHERE fingerprint IS NOT NULL;
